# Generated by Django 2.1.7 on 2019-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
    ]
